#!/usr/bin/env python3
"""build_moc.py - generate Map-of-Content hub pages to connect the wiki graph.

For each domain under wiki/techniques/, clusters pages by name-prefix and writes
<domain>/<domain>-moc.md linking every page (so none stay orphaned). Also writes
a top-level wiki/moc.md linking all domain MOCs + tools/cheatsheets + reuse lists.

Idempotent: regenerate any time. Does NOT touch CTF or courses. Does not edit
existing pages - only (re)writes the *-moc.md hubs.

  python3 scripts/build_moc.py
"""
import os
import re
import sys
from collections import defaultdict

VAULT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
WIKI = os.path.join(VAULT, "wiki")
TECH = os.path.join(WIKI, "techniques")
EXCLUDE_DOMAINS = {"CTF", "courses"}

# longer, known prefixes -> human label (checked longest-first)
PREFIX_LABELS = {
    "active-directory-certificate": "ADCS (Certificate Services)",
    "active-directory-federation": "AD Federation Services",
    "active-directory": "Active Directory core",
    "aws-service": "AWS services",
    "aws": "AWS",
    "azure-ad": "Azure AD / Entra",
    "azure-services": "Azure services",
    "azure": "Azure",
    "kubernetes": "Kubernetes",
    "cicd": "CI/CD",
    "gcp": "GCP",
    "cobalt-strike": "Cobalt Strike",
    "mssql": "MSSQL",
    "kerberos": "Kerberos",
    "network-pivoting": "Pivoting",
}


def humanize(key):
    return PREFIX_LABELS.get(key, key.replace("-", " ").title())


def group_key(slug):
    toks = slug.split("-")
    for n in (3, 2):
        p = "-".join(toks[:n])
        if p in PREFIX_LABELS:
            return p
    # fall back to 2-token prefix, else single token
    return "-".join(toks[:2]) if len(toks) >= 2 else toks[0]


def pages_in(domain_dir):
    out = []
    for f in os.listdir(domain_dir):
        if f.endswith(".md") and not f.endswith("-moc.md"):
            out.append(f[:-3])
    return sorted(out)


def build_domain_moc(domain):
    ddir = os.path.join(TECH, domain)
    pages = pages_in(ddir)
    if not pages:
        return None
    groups = defaultdict(list)
    for slug in pages:
        groups[group_key(slug)].append(slug)
    # singletons with a non-known key -> Misc
    misc = []
    clean = {}
    for k, v in groups.items():
        if len(v) == 1 and k not in PREFIX_LABELS:
            misc.extend(v)
        else:
            clean[k] = v
    label = domain.replace("-", " ").title()
    lines = [
        "---",
        f'title: "{label} - Map of Content"',
        "type: moc",
        f"tags: [moc, {domain}]",
        "sources: []",
        "---",
        "",
        f"# {label} - Map of Content",
        "",
        f"Hub for the **{domain}** techniques. Auto-generated by `scripts/build_moc.py`; "
        "re-run after adding pages.",
        "",
    ]
    for k in sorted(clean, key=lambda k: (-len(clean[k]), k)):
        lines.append(f"## {humanize(k)}")
        lines.append("")
        for slug in sorted(clean[k]):
            lines.append(f"- [[{slug}]]")
        lines.append("")
    if misc:
        lines.append("## Other")
        lines.append("")
        for slug in sorted(misc):
            lines.append(f"- [[{slug}]]")
        lines.append("")
    dest = os.path.join(ddir, f"{domain}-moc.md")
    open(dest, "w", encoding="utf-8").write("\n".join(lines))
    return domain, len(pages), os.path.relpath(dest, WIKI)


def main():
    domains = sorted(
        d for d in os.listdir(TECH)
        if os.path.isdir(os.path.join(TECH, d)) and d not in EXCLUDE_DOMAINS
    )
    built = []
    for dom in domains:
        r = build_domain_moc(dom)
        if r:
            built.append(r)
            print(f"  {r[0]:20} {r[1]:3} pages -> {r[2]}")

    # top-level MOC
    top = [
        "---",
        'title: "TORCH Wiki - Map of Content"',
        "type: moc",
        "tags: [moc, index]",
        "sources: []",
        "---",
        "",
        "# Wiki - Map of Content",
        "",
        "Top-level hub. Each domain has its own MOC linking every page.",
        "",
        "## Technique domains",
        "",
    ]
    for dom, n, rel in built:
        top.append(f"- [[{dom}-moc|{dom.replace('-', ' ').title()}]] ({n})")
    top += [
        "",
        "## Reference",
        "",
        "- [[index|Full page catalog]] - flat index of every page",
        "- [[default-credentials|Default credentials]] - product defaults, reuse across engagements",
        "- [[api-request-findings|API request findings]] - reusable request patterns",
        "- Tools: see `wiki/tools/`",
        "- Cheatsheets: see `wiki/cheatsheets/`",
        "",
    ]
    pdir = os.path.join(WIKI, "payloads")
    if os.path.isdir(pdir):
        top += ["## Payloads (arsenal)", ""]
        for f in sorted(os.listdir(pdir)):
            if f.endswith(".md"):
                top.append(f"- [[{f[:-3]}]]")
        top.append("")
    open(os.path.join(WIKI, "moc.md"), "w", encoding="utf-8").write("\n".join(top))
    print(f"  top-level -> moc.md ({len(built)} domains)")


if __name__ == "__main__":
    main()
