#!/usr/bin/env python3
"""gen_index.py - regenerate wiki/index.md as a complete, accurate page catalog.

Walks wiki/ and writes one table row per page (every page, not a curated
subset), grouped by section. Pulls title/tags/phase from frontmatter. This
replaces the old hand-maintained index that drifted to ~1/3 coverage.

Idempotent and self-maintaining: re-run any time (the SessionStart hook
regenerates it automatically when it goes stale). Curated graph navigation
lives in moc.md (build_moc.py); semantic navigation is qmd search. This file
is the flat fallback catalog.

  python3 scripts/gen_index.py            # rewrite wiki/index.md
  python3 scripts/gen_index.py --check    # exit 1 if index.md is stale (no write)
"""
import os
import re
import sys

VAULT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
WIKI = os.path.join(VAULT, "wiki")
INDEX = os.path.join(WIKI, "index.md")

# pages that are navigation/meta, not catalog content
SKIP_BASENAMES = {"index", "moc", "overview"}

FM_RE = re.compile(r"^---\r?\n(.*?)\r?\n---", re.S)   # tolerate CRLF (this vault lives on /mnt/c)


def frontmatter(path):
    """Return dict with title/tags/phase/type parsed from YAML frontmatter (stdlib only)."""
    text = open(path, encoding="utf-8", errors="ignore").read(4096)
    m = FM_RE.match(text)
    fm = {"title": "", "tags": "", "phase": "", "type": ""}
    if not m:
        return fm
    body = m.group(1)
    in_tags = False        # inside a block-form `tags:\n  - a\n  - b`
    block_tags = []
    for line in body.splitlines():
        if in_tags:
            mb = re.match(r"\s*-\s+(.+)", line)
            if mb:
                block_tags.append(mb.group(1).strip().strip('"').strip("'"))
                continue
            in_tags = False    # a non-bullet line ends the block
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key == "title":
            fm["title"] = val
        elif key == "type":
            fm["type"] = val
        elif key == "phase":
            fm["phase"] = val
        elif key == "tags":
            if val:
                fm["tags"] = val.strip("[]").strip()   # inline: tags: [a, b, c]
            else:
                in_tags = True                          # block form follows
    if block_tags and not fm["tags"]:
        fm["tags"] = ", ".join(block_tags)
    return fm


def md_pages(base):
    """Yield (slug, frontmatter) for catalog pages under base, sorted by slug."""
    out = []
    for root, _, files in os.walk(base):
        for f in sorted(files):
            if not f.endswith(".md"):
                continue
            slug = f[:-3]
            if slug in SKIP_BASENAMES or slug.endswith("-moc"):
                continue
            out.append((slug, frontmatter(os.path.join(root, f))))
    return sorted(out, key=lambda x: x[0])


def table(pages):
    rows = ["| Page | Tags | Phase |", "|------|------|-------|"]
    for slug, fm in pages:
        rows.append(f"| [[{slug}]] | {fm['tags']} | {fm['phase']} |")
    return rows


def build():
    lines = [
        "---",
        'title: "Wiki Index"',
        "type: overview",
        "tags: [meta, index]",
        "sources: []",
        "---",
        "",
        "# Wiki Index",
        "",
        "Complete catalog of every page. **Auto-generated by `scripts/gen_index.py` "
        "- do not hand-edit** (the SessionStart hook regenerates it when stale).",
        "",
        "**Navigate by graph:** [[moc|Map of Content]] - domain hubs. "
        "**Search:** `qmd query` (semantic) / `qmd keyword` (exact) - preferred over reading this file.",
        "",
        "---",
        "",
        "## Techniques",
        "",
    ]
    tech = os.path.join(WIKI, "techniques")
    for area in sorted(os.listdir(tech)):
        adir = os.path.join(tech, area)
        if not os.path.isdir(adir):
            continue
        pages = md_pages(adir)
        if not pages:
            continue
        label = area.replace("-", " ").title()
        lines += [f"### {label} ({len(pages)})", ""]
        lines += table(pages)
        lines += [""]

    for section, sub in [
        ("Tools", "tools"),
        ("Cheatsheets", "cheatsheets"),
        ("Payloads", "payloads"),
        ("Courses", "courses"),
        ("CTF", "CTF"),
    ]:
        sdir = os.path.join(WIKI, sub)
        if not os.path.isdir(sdir):
            continue
        pages = md_pages(sdir)
        if not pages:
            continue
        lines += ["---", "", f"## {section} ({len(pages)})", ""]
        lines += table(pages)
        lines += [""]

    return "\n".join(lines).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    new = build()
    cur = open(INDEX, encoding="utf-8", errors="ignore").read() if os.path.exists(INDEX) else ""
    if check:
        if new != cur:
            print("index.md STALE (run scripts/gen_index.py)")
            return 1
        print("index.md current")
        return 0
    if new == cur:
        print("wiki/index.md already current")
        return 0
    open(INDEX, "w", encoding="utf-8").write(new)
    n = new.count("| [[")
    print(f"wrote wiki/index.md ({n} pages cataloged)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
